ApiConsume/Controllers/CityController.cs
using ApiConsume.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;


namespace ApiConsume.Controllers
{
    public class CityController : Controller
    {
        #region Configuation
        private readonly HttpClient _httpClient;
        Uri baseAddress = new Uri("http://localhost:41349/api");

        public CityController()
        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = baseAddress;
        }
        #endregion


        #region CityList
        public  List<CityModel> GetAllCities(int? filterID)
        {
            List<CityModel> cities = new List<CityModel>();
            int filterby = filterID ?? -999;
            HttpResponseMessage response = _httpClient.GetAsync($"{_httpClient.BaseAddress}/City/cities/{filterby}").Result;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                cities = JsonConvert.DeserializeObject<List<CityModel>>(data);
            }
            return cities;
        }
        #endregion

        public IActionResult CityList(int? filterID) {

            var data = GetAllCities(filterID);
            ViewBag.Data = data;
            if(filterID == null)
            {
                ViewBag.Cstae = "All";
            }
            else
            {
                if (data.Count != 0)
                    ViewBag.cstae = data[0].StateName;
                else
                    ViewBag.cstae = "No Data";
            }
            return View();
        }

        #region CityAdd
        public async Task<IActionResult> CityAddEdit(int? CityID)
        {
            await LoadCountryList();
            if (CityID.HasValue)
            {
                var response = await _httpClient.GetAsync($"{_httpClient.BaseAddress}/City/{CityID}");
                if (response.IsSuccessStatusCode)
                {
                    var data = await response.Content.ReadAsStringAsync();
                    var city = JsonConvert.DeserializeObject<CityModel>(data);
                    ViewBag.StateList = await GetStatesByCountryID(city.CountryID);
                    return View(city);
                }
            }
            return View(new CityModel());
        }
        #endregion

        #region CitySave
        [HttpPost]
        public async Task<IActionResult> CitySave(CityModel city)
        {
            if (ModelState.IsValid)
            {
                var json = JsonConvert.SerializeObject(city);
                var content = new StringContent(json, Encoding.UTF8, "application/json");
                HttpResponseMessage response;

                if (city.CityID == null || city.CityID == 0)
                    response = await _httpClient.PostAsync($"{_httpClient.BaseAddress}/City", content);
                else
                    response = await _httpClient.PutAsync($"{_httpClient.BaseAddress}/City/{city.CityID}", content);

                if (response.IsSuccessStatusCode)
                    return RedirectToAction("CityList");
            }
            await LoadCountryList();
            return View("CityAddEdit", city);
        }
        #endregion

        #region CityDelete
        public async Task<IActionResult> CityDelete(int CityID)
        {
            var response = await _httpClient.DeleteAsync($"{_httpClient.BaseAddress}/City/{CityID}");
            return RedirectToAction("CityList");
        }
        #endregion

        #region LoadCountryList
        private async Task LoadCountryList()
        {
            var response = await _httpClient.GetAsync($"{_httpClient.BaseAddress}/Country/countries");
            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                var countries = JsonConvert.DeserializeObject<List<CountryDropDownModel>>(data);
                ViewBag.CountryList = countries;
            }
        }
        #endregion

        #region GetStatesByCountry
        [HttpPost]
        public async Task<JsonResult> GetStatesByCountry(int CountryID)
        {
            var states = await GetStatesByCountryID(CountryID);
            return Json(states);
        }
        #endregion

        #region GetStatesByCountryID
        private async Task<List<StateDropDownModel>> GetStatesByCountryID(int CountryID)
        {
            var response = await _httpClient.GetAsync($"{_httpClient.BaseAddress}/Country/States/{CountryID}");
            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                return JsonConvert.DeserializeObject<List<StateDropDownModel>>(data);
            }
            return new List<StateDropDownModel>();
        }
        #endregion
    }
}

ApiConsume/Controllers/StateController.cs
using ApiConsume.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace ApiConsume.Controllers
{
    public class StateController : Controller
    {
        #region Configiuration
        private readonly HttpClient _httpClient;
        Uri baseAddress = new Uri("http://localhost:41349/api");

        public StateController()
        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = baseAddress;
        }
        #endregion

        #region StateList
        [HttpGet]
        public IActionResult StateList()
        {
            List<StateModel> states = new List<StateModel>();
            HttpResponseMessage response = _httpClient.GetAsync($"{_httpClient.BaseAddress}/State").Result;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                dynamic jsonObject = JsonConvert.DeserializeObject<dynamic>(data);
                var extractedDataJson = JsonConvert.SerializeObject(jsonObject, Formatting.Indented);

                states = JsonConvert.DeserializeObject<List<StateModel>>(extractedDataJson);
            }
            return View("StateList", states);
        }
        #endregion

        //[HttpDelete("{CountryID}")]
        #region StateDelete
        public async Task<IActionResult> StateDelete(int StateID)
        {
            try
            {

                HttpResponseMessage response = await _httpClient.DeleteAsync($"{_httpClient.BaseAddress}/State/{StateID}");

                if (response.IsSuccessStatusCode)
                {
                    TempData["Success"] = "State deleted successfully.";
                }
                else
                {
                    TempData["ErrorMessage"] = $"Failed to delete the State. Status Code: {response.StatusCode}";
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"An error occurred: {ex.Message}";
            }

            return RedirectToAction("StateList");
        }
        #endregion

        #region StateAddEdit
        public async Task<IActionResult> StateAddEdit(int? StateID)
        {
            await LoadCountryList();
            if (StateID.HasValue)
            {
                var response = await _httpClient.GetAsync($"{_httpClient.BaseAddress}/State/{StateID}");
                if (response.IsSuccessStatusCode)
                {
                    var data = await response.Content.ReadAsStringAsync();
                    var state = JsonConvert.DeserializeObject<StateModel>(data);
                    return View(state);
                }
            }
            return View(new StateModel());
        }
        #endregion

        #region StateSave
        [HttpPost]
        public async Task<IActionResult> StateSave(StateModel state)
        {
            await LoadCountryList();
            if (ModelState.IsValid)
            {
                var json = JsonConvert.SerializeObject(state);
                var content = new StringContent(json, Encoding.UTF8, "application/json");
                HttpResponseMessage response;

                if (state.StateID== null || state.StateID==0)
                    response = await _httpClient.PostAsync($"{_httpClient.BaseAddress}/State", content);
                else
                    response = await _httpClient.PutAsync($"{_httpClient.BaseAddress}/State/{state.StateID}", content);

                if (response.IsSuccessStatusCode)
                    return RedirectToAction("StateList");
            }
            return View("StateAddEdit", state);
        }
        #endregion

        #region LoadCountryList
        private async Task LoadCountryList()
        {
            var response = await _httpClient.GetAsync($"{_httpClient.BaseAddress}/Country/countries");
            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                var countries = JsonConvert.DeserializeObject<List<CountryDropDownModel>>(data);
                ViewBag.CountryList = countries;
            }
        }
        #endregion


    }
}

ApiConsume/Views/State/StateAddEdit.cshtml
@model StateModel

<div class="card">
    <div class="card-body">
        <h5 class="card-title">@((Model.StateID > 0) ? "Edit" : "Add New") State</h5>


        <!-- Multi Columns Form -->
        <form class="row g-3" asp-controller="State" asp-action="StateSave">
            @Html.HiddenFor(x => x.StateID)
            <div class="col-md-6">
                <label class="form-label" asp-for="StateName">State Name<span class="text-danger">*</span></label>
                <input type="text" class="form-control" asp-for="StateName" />
                <span asp-validation-for="StateName" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <label asp-for="StateCode" class="form-label">State Code<span class="text-danger">*</span></label>
                <input type="text" class="form-control" asp-for="StateCode">
                <span asp-validation-for="StateCode" class="text-danger"></span>
            </div>

            <div class="col-md-6">
                <label asp-for="CountryID" class="form-label">Country Name<span class="text-danger">*</span></label>
                @*  <select class="form-control" asp-for="CountryID" asp-items="@(new SelectList(ViewBag.CountryList, "CountryID", "CountryName"))">
                <option value="">Select Country</option>
                </select> *@
                <select id="CountryID"
                        name="CountryID"
                        class="form-control"
                        asp-for="CountryID">
                    <option value="">Select Country</option>
                    @foreach (var country in ViewBag.CountryList)
                    {
                        <option value="@country.CountryID">
                            @country.CountryName
                        </option>
                    }
                </select>
                <span asp-validation-for="CountryID" class="text-danger"></span>
            </div>


            <div class="row">

                @if (Model.StateID == null || Model.StateID == 0)
                {
                    <button type="submit" class="btn btn-outline-success mt-3 me-3 col-2">Add State</button>
                }
                else
                {
                    <button type="submit" class="btn btn-outline-success mt-3 me-3 col-2">Update State</button>
                }
                <a asp-action="StateList" asp-controller="State" class="btn btn-outline-warning mt-3 col-2">Back To List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ApiConsume/Views/State/StateList.cshtml
@using System.Data;
@model IEnumerable<ApiConsume.Models.StateModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section>
    <span><h3>State List</h3></span>
    @if (TempData["Success"] != null)
    {
        <div class="alert alert-success text-success">
            @TempData["Success"]
        </div>
    }
    @if (TempData["ErrorMessage"] != null)
    {
        <div class="alert alert-danger text-danger">
            @TempData["ErrorMessage"]
        </div>
    }
    <div class="float-end">
        <a class="btn btn-primary mb-3" asp-controller="State" asp-action="StateAddEdit">Add State</a>
        @* <a class="btn btn-info mb-3" asp-controller="ExportToExcel" asp-action="ExportToExcel" asp-route-table="User"><i class="bi bi-filetype-xlsx"></i>Export</a> *@
    </div>

    <div class="mb-3">
        <input type="text" class="form-control" id="stateSearch" placeholder="Search State">
    </div>

    <table class="table table-striped">
        <thead>
            <tr>
                <!-- <th scope="col">UserID</th> -->
                <th scope="col">State Name</th>
                <th scope="col">State Code</th>
                <th scope="col">City Count</th>
                 <th scope="col">Country Name</th>
                @* <th scope="col">Created Date</th>
                <th scope="col">Modified Date</th> *@
                <th colspan="2">Actions</th>

            </tr>
        </thead>
        <tbody id="stateTable">
            @foreach (var dr in Model)
            {
                <tr>
                    <!-- <td scope="col">dr.UserID</td> -->
                    <td scope="col">@dr.StateName</td>
                    <td scope="col">@dr.StateCode</td>
                    <td scope="col">
                        <a class="text-info text-decoration-none fw-bold bg-primary p-1 rounded-3" asp-controller="City" asp-action="CityList" asp-route-filterID="@dr.StateID" >
                            @dr.CityCount
                        </a>

                    <td scope="col">@dr.CountryName</td> 
                    @* <td scope="col">@dr.CreatedDate</td>
                    <td scope="col">@dr.ModifiedDate</td> *@
                    </td>
                    <td>
                        <a class="btn btn-outline-success" asp-controller="State" asp-action="StateAddEdit" asp-route-StateID="@dr.StateID">
                            <i class="bi bi-pen-fill"></i>
                        </a>
                    </td>
                    <td>

                    <td>


                        <form method="post" asp-controller="State" asp-action="StateDelete">
                            <input type="hidden" name="StateID" value=@dr.StateID />
                            <button type="submit" class="btn btn-outline-danger btn-xs" onclick="return confirm('Sure!! Are you want to delete @dr.StateName')">
                                <i class="bi bi-x"></i>
                            </button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</section>

@section Scripts {
    <script>
        $(document).ready(function () {
            $("#stateSearch").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#stateTable tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1);
                });
            });
        });
    </script>
}